#Requires -Modules @{ ModuleName = 'Pester'; ModuleVersion = '5.0.0' }

# Tests für die testbare Kernfunktion des init-Generators: New-GitBulkConfigYaml.
# Der interaktive Teil (Invoke-GitBulkInit, Read-Host) ist bewusst nicht getestet
# (nur im echten Terminal sinnvoll). Geprüft wird, dass das erzeugte YAML
# vollständig durch Get-GitBulkConfig validiert (Round-Trip).

BeforeAll {
    Import-Module (Join-Path $PSScriptRoot '..' 'GitBulk.psd1') -Force
    $script:tmp = Join-Path ([System.IO.Path]::GetTempPath()) ('gb-init-' + [guid]::NewGuid().ToString('N'))
    New-Item -ItemType Directory -Path $script:tmp | Out-Null
}

AfterAll {
    Remove-Item -Recurse -Force -ErrorAction SilentlyContinue $script:tmp
}

Describe 'New-GitBulkConfigYaml' {
    It 'writes a header and never leaks tokens' {
        $yaml = New-GitBulkConfigYaml -Rus @('r') -Ticket 'AKB-1' -Branch 'b' -CommitMessage 'm' `
            -PrSummary 's' -Operations @([ordered]@{ type = 'delete-file'; path = 'x' })
        $yaml | Should -Match '# Generated by'
        $yaml | Should -Match 'GITBULK_BITBUCKET_TOKEN'
        $yaml | Should -Not -Match 'TOKEN:.*\S'   # kein Token-Wert in der Config
    }

    It 'produces a bitbucket config that round-trips through Get-GitBulkConfig' {
        $ops = @(
            [ordered]@{ type = 'add-file'; path = 'NOTICE'; content = 'hi' }
            [ordered]@{ type = 'json-patch'; path = 'package.json'; pointer = 'scripts.build'; value = 'tsc' }
        )
        $yaml = New-GitBulkConfigYaml -Rus @('repo-a', 'repo-b') -Ticket 'AKB-1' -Branch 'feature/x' `
            -CommitMessage 'msg' -PrSummary 'summary' -Operations $ops -PrPlatform 'bitbucket' -BitbucketWorkspace 'ws'
        $file = Join-Path $script:tmp 'bb.yaml'
        [System.IO.File]::WriteAllText($file, $yaml)

        $cfg = Get-GitBulkConfig -Path $file
        $cfg.rus | Should -Be @('repo-a', 'repo-b')
        $cfg.ticket | Should -Be 'AKB-1'
        $cfg.prPlatform | Should -Be 'bitbucket'
        $cfg.bitbucket.workspace | Should -Be 'ws'
        $cfg.operations.Count | Should -Be 2
        $cfg.operations[0]['type'] | Should -Be 'add-file'
        $cfg.operations[1]['pointer'] | Should -Be 'scripts.build'
    }

    It 'produces a github config that round-trips' {
        $yaml = New-GitBulkConfigYaml -Rus @('r') -Ticket 'AKB-2' -Branch 'feat/y' -CommitMessage 'm' `
            -PrSummary 's' -Operations @([ordered]@{ type = 'delete-file'; path = 'old.txt' }) `
            -PrPlatform 'github' -GitHubOwner 'acme'
        $file = Join-Path $script:tmp 'gh.yaml'
        [System.IO.File]::WriteAllText($file, $yaml)

        $cfg = Get-GitBulkConfig -Path $file
        $cfg.prPlatform | Should -Be 'github'
        $cfg.github.owner | Should -Be 'acme'
        $cfg.operations[0]['type'] | Should -Be 'delete-file'
    }

    It 'produces a gitlab config that round-trips (targetBranch main, correct token var)' {
        $yaml = New-GitBulkConfigYaml -Rus @('r') -Ticket 'AKB-4' -Branch 'feat/z' -CommitMessage 'm' `
            -PrSummary 's' -Operations @([ordered]@{ type = 'delete-file'; path = 'x' }) `
            -PrPlatform 'gitlab' -GitLabNamespace 'my-group'
        $yaml | Should -Match 'GITBULK_GITLAB_TOKEN'
        $file = Join-Path $script:tmp 'gl.yaml'
        [System.IO.File]::WriteAllText($file, $yaml)

        $cfg = Get-GitBulkConfig -Path $file
        $cfg.prPlatform | Should -Be 'gitlab'
        $cfg.gitlab.namespace | Should -Be 'my-group'
        $cfg.gitlab.targetBranch | Should -Be 'main'
    }

    It 'produces an azure-devops config that round-trips (targetBranch master, correct token var)' {
        $yaml = New-GitBulkConfigYaml -Rus @('r') -Ticket 'AKB-5' -Branch 'feat/a' -CommitMessage 'm' `
            -PrSummary 's' -Operations @([ordered]@{ type = 'delete-file'; path = 'x' }) `
            -PrPlatform 'azure-devops' -AzureOrganization 'my-org' -AzureProject 'my-proj'
        $yaml | Should -Match 'GITBULK_AZURE_DEVOPS_TOKEN'
        $file = Join-Path $script:tmp 'az.yaml'
        [System.IO.File]::WriteAllText($file, $yaml)

        $cfg = Get-GitBulkConfig -Path $file
        $cfg.prPlatform | Should -Be 'azure-devops'
        $cfg.azureDevOps.organization | Should -Be 'my-org'
        $cfg.azureDevOps.project | Should -Be 'my-proj'
        $cfg.azureDevOps.targetBranch | Should -Be 'master'
    }

    It 'reflects createPrOnError and defaults sourceBranch to master' {
        $yaml = New-GitBulkConfigYaml -Rus @('r') -Ticket 'AKB-3' -Branch 'b' -CommitMessage 'm' `
            -PrSummary 's' -Operations @([ordered]@{ type = 'delete-file'; path = 'x' }) -CreatePrOnError $true
        $file = Join-Path $script:tmp 'c.yaml'
        [System.IO.File]::WriteAllText($file, $yaml)

        $cfg = Get-GitBulkConfig -Path $file
        $cfg.createPrOnError | Should -BeTrue
        $cfg.sourceBranch | Should -Be 'master'
    }
}
