function New-GitBulkConfigYaml {
    <#
    .SYNOPSIS
        Baut aus den gesammelten Werten eine lauffähige GitBulk-YAML-Config mit
        `operations:`-Block (Pendant zu generateYamlConfig in der Node-Version).

    .DESCRIPTION
        Reine, prompt-freie Logik (daher unit-testbar): nimmt die gesammelten
        Felder + Operationen, baut ein geordnetes Config-Objekt und serialisiert
        es nach YAML (via powershell-yaml). Der interaktive Generator
        (Invoke-GitBulkInit) sammelt die Werte und ruft diese Funktion auf.

        Tokens werden NIE in die Config geschrieben — sie kommen zur Laufzeit aus
        Umgebungsvariablen.

    .PARAMETER Operations
        Liste der Operationen als Dictionaries inkl. 'type'-Schlüssel.

    .PARAMETER PrPlatform
        'bitbucket' (Default) oder 'github'. Bestimmt den erzeugten Plattform-Block.
    #>
    [CmdletBinding()]
    [OutputType([string])]
    param(
        [Parameter(Mandatory)][string[]]$Rus,
        [Parameter(Mandatory)][string]$Ticket,
        [Parameter(Mandatory)][string]$Branch,
        [Parameter(Mandatory)][string]$CommitMessage,
        [Parameter(Mandatory)][string]$PrSummary,
        [Parameter(Mandatory)][object[]]$Operations,

        [ValidateSet('bitbucket', 'github')][string]$PrPlatform = 'bitbucket',
        [string]$SourceBranch = 'master',
        [bool]$CreatePrOnError = $false,
        [string]$BitbucketWorkspace = 'YOUR_WORKSPACE',
        [string]$GitHubOwner = 'YOUR_ORG'
    )

    if (-not (Get-Module -ListAvailable -Name 'powershell-yaml')) {
        throw "Generating a YAML config requires the 'powershell-yaml' module (Install-Module powershell-yaml)."
    }
    Import-Module powershell-yaml -ErrorAction Stop

    # Operationen geordnet aufbauen ('type' zuerst, dann die übrigen Parameter).
    $ops = @(
        foreach ($o in $Operations) {
            $od = [ordered]@{ type = [string]$o['type'] }
            foreach ($k in $o.Keys) { if ($k -ne 'type') { $od[[string]$k] = $o[$k] } }
            $od
        }
    )

    $config = [ordered]@{
        rus             = @($Rus)
        ticket          = $Ticket
        branch          = $Branch
        sourceBranch    = $SourceBranch
        operations      = $ops
        commitMessage   = $CommitMessage
        prSummary       = $PrSummary
        createPrOnError = $CreatePrOnError
        prPlatform      = $PrPlatform
    }
    if ($PrPlatform -eq 'bitbucket') {
        $config.bitbucket = [ordered]@{ workspace = $BitbucketWorkspace; targetBranch = 'master' }
    } else {
        $config.github = [ordered]@{ owner = $GitHubOwner; targetBranch = 'main' }
    }

    $header = @(
        '# Generated by `gitbulk.ps1 -Init`.'
        '# Run with: ./gitbulk.ps1 -Config <this-file>'
        '# The PR token is read from an env var (GITBULK_BITBUCKET_TOKEN /'
        '# GITBULK_GITHUB_TOKEN), never from the config.'
        ''
    ) -join "`n"

    return $header + (ConvertTo-Yaml $config)
}
