function New-GitBulkConfigYaml {
    <#
    .SYNOPSIS
        Baut aus den gesammelten Werten eine lauffähige GitBulk-YAML-Config mit
        `operations:`-Block (Pendant zu generateYamlConfig in der Node-Version).

    .DESCRIPTION
        Reine, prompt-freie Logik (daher unit-testbar): nimmt die gesammelten
        Felder + Operationen, baut ein geordnetes Config-Objekt und serialisiert
        es nach YAML (via powershell-yaml). Der interaktive Generator
        (Invoke-GitBulkInit) sammelt die Werte und ruft diese Funktion auf.

        Tokens werden NIE in die Config geschrieben — sie kommen zur Laufzeit aus
        Umgebungsvariablen.

    .PARAMETER Operations
        Liste der Operationen als Dictionaries inkl. 'type'-Schlüssel.

    .PARAMETER PrPlatform
        'bitbucket' (Default), 'github', 'gitlab' oder 'azure-devops'.
        Bestimmt den erzeugten Plattform-Block.
    #>
    [CmdletBinding()]
    [OutputType([string])]
    param(
        [Parameter(Mandatory)][string[]]$Rus,
        [Parameter(Mandatory)][string]$Ticket,
        [Parameter(Mandatory)][string]$Branch,
        [Parameter(Mandatory)][string]$CommitMessage,
        [Parameter(Mandatory)][string]$PrSummary,
        [Parameter(Mandatory)][object[]]$Operations,

        [ValidateSet('bitbucket', 'github', 'gitlab', 'azure-devops')][string]$PrPlatform = 'bitbucket',
        [string]$SourceBranch = 'master',
        [bool]$CreatePrOnError = $false,
        [string]$BitbucketWorkspace = 'YOUR_WORKSPACE',
        [string]$GitHubOwner = 'YOUR_ORG',
        [string]$GitLabNamespace = 'YOUR_NAMESPACE',
        [string]$AzureOrganization = 'YOUR_ORGANIZATION',
        [string]$AzureProject = 'YOUR_PROJECT'
    )

    if (-not (Get-Module -ListAvailable -Name 'powershell-yaml')) {
        throw "Generating a YAML config requires the 'powershell-yaml' module (Install-Module powershell-yaml)."
    }
    Import-Module powershell-yaml -ErrorAction Stop

    # Operationen geordnet aufbauen ('type' zuerst, dann die übrigen Parameter).
    $ops = @(
        foreach ($o in $Operations) {
            $od = [ordered]@{ type = [string]$o['type'] }
            foreach ($k in $o.Keys) { if ($k -ne 'type') { $od[[string]$k] = $o[$k] } }
            $od
        }
    )

    $config = [ordered]@{
        rus             = @($Rus)
        ticket          = $Ticket
        branch          = $Branch
        sourceBranch    = $SourceBranch
        operations      = $ops
        commitMessage   = $CommitMessage
        prSummary       = $PrSummary
        createPrOnError = $CreatePrOnError
        prPlatform      = $PrPlatform
    }
    # Sub-Block je Plattform. targetBranch-Defaults folgen dem Schema
    # (Bitbucket/Azure: master, GitHub/GitLab: main).
    switch ($PrPlatform) {
        'bitbucket' { $config.bitbucket = [ordered]@{ workspace = $BitbucketWorkspace; targetBranch = 'master' } }
        'github' { $config.github = [ordered]@{ owner = $GitHubOwner; targetBranch = 'main' } }
        'gitlab' { $config.gitlab = [ordered]@{ namespace = $GitLabNamespace; targetBranch = 'main' } }
        'azure-devops' { $config.azureDevOps = [ordered]@{ organization = $AzureOrganization; project = $AzureProject; targetBranch = 'master' } }
    }

    $tokenVar = switch ($PrPlatform) {
        'bitbucket' { 'GITBULK_BITBUCKET_TOKEN' }
        'github' { 'GITBULK_GITHUB_TOKEN' }
        'gitlab' { 'GITBULK_GITLAB_TOKEN' }
        'azure-devops' { 'GITBULK_AZURE_DEVOPS_TOKEN' }
    }
    $header = @(
        '# Generated by `gitbulk.ps1 -Init`.'
        '# Run with: ./gitbulk.ps1 -Config <this-file>'
        "# The PR token is read from the $tokenVar env var, never from the config."
        ''
    ) -join "`n"

    return $header + (ConvertTo-Yaml $config)
}
