/**
 * Baut aus den interaktiv gesammelten Werten eine lauffähige GitBulk-Config
 * (für `gitbulk init`, Config-Modus) und serialisiert sie nach YAML.
 *
 * Der Code-Change ist GENAU EINES von `operations:` (deklarativ) ODER `script:`
 * (Pfad zu einem generierten/eigenen Skript — der „beides"-Modus von `init`).
 */

import { Document, Scalar } from 'yaml';

export interface ConfigGeneratorInput {
  rus: string[];
  ticket: string;
  branch: string;
  commitMessage: string;
  prSummary: string;
  createPrOnError: boolean;
  /**
   * Die zusammengeklickten Operationen (inkl. `type`). GENAU EINES von
   * `operations` / `script` setzen — `script` hat Vorrang, wenn beide gesetzt sind.
   */
  operations?: Array<{ type: string } & Record<string, unknown>>;
  /** Pfad zu einem Code-Change-Skript (Alternative zu `operations`). */
  script?: string;
  /** PR-Plattform (aktuell genügt Bitbucket). */
  prPlatform: 'bitbucket' | 'azure-devops';
  /** Bitbucket-Workspace (Pflicht bei prPlatform === 'bitbucket'). */
  bitbucketWorkspace?: string;
}

/**
 * Erzeugt das Config-Objekt (vor der YAML-Serialisierung).
 * Reihenfolge der Schlüssel ist bewusst lesefreundlich gewählt.
 */
export function buildConfigObject(input: ConfigGeneratorInput): Record<string, unknown> {
  // Code-Change: `script` hat Vorrang (beides-Modus), sonst `operations`.
  const codeChange =
    input.script !== undefined ? { script: input.script } : { operations: input.operations ?? [] };
  const config: Record<string, unknown> = {
    rus: input.rus,
    ticket: input.ticket,
    branch: input.branch,
    ...codeChange,
    commitMessage: input.commitMessage,
    prSummary: input.prSummary,
    createPrOnError: input.createPrOnError,
    prPlatform: input.prPlatform,
  };

  if (input.prPlatform === 'bitbucket') {
    config.bitbucket = {
      workspace: input.bitbucketWorkspace ?? 'YOUR_WORKSPACE',
      targetBranch: 'master',
    };
  }

  return config;
}

/**
 * Erzwingt für einen Top-Level-String-Schlüssel doppelte Anführungszeichen in
 * der YAML-Ausgabe (Auto-Quotes). So sind Freitext-Felder wie `commitMessage`
 * immer eindeutig als String gequotet — auch wenn der Text Sonderzeichen wie
 * `:` enthält oder als Zahl/Bool fehlinterpretiert werden könnte.
 */
function forceDoubleQuote(doc: Document, key: string): void {
  const node: unknown = doc.get(key, true);
  if (node instanceof Scalar) {
    node.type = Scalar.QUOTE_DOUBLE;
  }
}

/**
 * Serialisiert die Config als YAML-String (mit erklärendem Kopf-Kommentar).
 */
export function generateYamlConfig(input: ConfigGeneratorInput): string {
  const header =
    '# Generated by `gitbulk init`.\n' +
    '# Run with: gitbulk --config <this-file>\n' +
    '# The Bitbucket token is read from the GITBULK_BITBUCKET_TOKEN env var.\n';
  const doc = new Document(buildConfigObject(input));
  // Freitext-Felder immer doppelt quoten (Auto-Quotes).
  forceDoubleQuote(doc, 'commitMessage');
  forceDoubleQuote(doc, 'prSummary');
  return `${header}${doc.toString()}`;
}
