/**
 * Baut aus den interaktiv gesammelten Werten eine lauffähige GitBulk-Config
 * (für `gitbulk init`, Config-Modus) und serialisiert sie nach YAML.
 *
 * Bewusst KEINE Skript-Felder — die `operations:` ersetzen das `script:`.
 */

import { stringify as stringifyYaml } from 'yaml';

export interface ConfigGeneratorInput {
  rus: string[];
  ticket: string;
  branch: string;
  commitMessage: string;
  prSummary: string;
  createPrOnError: boolean;
  /** Die zusammengeklickten Operationen (inkl. `type`). */
  operations: Array<{ type: string } & Record<string, unknown>>;
  /** PR-Plattform (aktuell genügt Bitbucket). */
  prPlatform: 'bitbucket' | 'azure-devops';
  /** Bitbucket-Workspace (Pflicht bei prPlatform === 'bitbucket'). */
  bitbucketWorkspace?: string;
}

/**
 * Erzeugt das Config-Objekt (vor der YAML-Serialisierung).
 * Reihenfolge der Schlüssel ist bewusst lesefreundlich gewählt.
 */
export function buildConfigObject(input: ConfigGeneratorInput): Record<string, unknown> {
  const config: Record<string, unknown> = {
    rus: input.rus,
    ticket: input.ticket,
    branch: input.branch,
    operations: input.operations,
    commitMessage: input.commitMessage,
    prSummary: input.prSummary,
    createPrOnError: input.createPrOnError,
    prPlatform: input.prPlatform,
  };

  if (input.prPlatform === 'bitbucket') {
    config.bitbucket = {
      workspace: input.bitbucketWorkspace ?? 'YOUR_WORKSPACE',
      targetBranch: 'master',
    };
  }

  return config;
}

/**
 * Serialisiert die Config als YAML-String (mit erklärendem Kopf-Kommentar).
 */
export function generateYamlConfig(input: ConfigGeneratorInput): string {
  const header =
    '# Generated by `gitbulk init`.\n' +
    '# Run with: gitbulk --config <this-file>\n' +
    '# The Bitbucket token is read from the GITBULK_BITBUCKET_TOKEN env var.\n';
  return `${header}${stringifyYaml(buildConfigObject(input))}`;
}
