/**
 * Generiert ein eigenständiges `.mjs`-Code-Change-Skript aus einer Liste
 * deklarativer Operationen (für `gitbulk init`, Skript-Modus).
 *
 * Jede Operation liefert ihren reinen-Node-Code via `generateScript(params)`
 * selbst (siehe `Operation`-Interface). Dieses Modul setzt nur die gemeinsame
 * Präambel (Imports, `repoDir`, `log`) davor und kapselt jede Operation in
 * einen eigenen Block, damit lokale Variablen sich nicht überschneiden.
 */

import { getOperation } from '../operations/index.js';

/** Eine zu generierende Operation: Typ + bereits geparste Parameter. */
export interface ScriptOperation {
  type: string;
  params: Record<string, unknown>;
}

export interface GenerateScriptResult {
  /** Der vollständige `.mjs`-Quelltext. */
  code: string;
  /** Operation-Typen ohne `generateScript` (im Skript als TODO markiert). */
  unsupported: string[];
}

const PREAMBLE = `#!/usr/bin/env node
// Generated by \`gitbulk init\`. Standalone code-change script — edit freely.
//
// GitBulk runs this with the repository as the working directory and sets
// GITBULK_RU / GITBULK_TICKET / GITBULK_BRANCH / GITBULK_SOURCE_BRANCH.
// Only modify files here — GitBulk performs git add / commit / push itself.
// Exit non-zero to signal a failed code change.
import { existsSync, readFileSync, writeFileSync, mkdirSync, rmSync, statSync } from 'node:fs';
import { join, dirname } from 'node:path';

const repoDir = process.cwd();
const log = (msg) => console.log('[gitbulk] ' + msg);`;

/** Rückt jede Zeile um zwei Leerzeichen ein. */
function indent(code: string): string {
  return code
    .split('\n')
    .map((line) => (line.length > 0 ? `  ${line}` : line))
    .join('\n');
}

/**
 * Baut den `.mjs`-Quelltext für die gegebene Operationskette.
 */
export function generateMjsScript(operations: ReadonlyArray<ScriptOperation>): GenerateScriptResult {
  const unsupported: string[] = [];
  const blocks: string[] = [];

  operations.forEach((op, idx) => {
    const registered = getOperation(op.type);
    const num = idx + 1;

    if (!registered || typeof registered.generateScript !== 'function') {
      unsupported.push(op.type);
      blocks.push(
        `// --- operation #${num}: ${op.type} ---\n` +
          `// NOTE: this operation has no script generator — implement it manually.`,
      );
      return;
    }

    const body = registered.generateScript(op.params as never);
    blocks.push(`// --- operation #${num}: ${op.type} ---\n{\n${indent(body)}\n}`);
  });

  const code = `${[PREAMBLE, '', ...blocks].join('\n')}\n`;
  return { code, unsupported };
}
