/**
 * Generiert ein eigenständiges Code-Change-Skript (`.mjs` oder `.ts`) aus einer
 * Liste deklarativer Operationen (für `gitbulk init`, Skript-Modus).
 *
 * Jede Operation liefert ihren reinen-Node-Code via `generateScript(params)`
 * selbst (siehe `Operation`-Interface). Dieses Modul setzt nur die gemeinsame
 * Präambel (Imports, `repoDir`, `log`) davor und kapselt jede Operation in
 * einen eigenen Block, damit lokale Variablen sich nicht überschneiden.
 *
 * Die pro-Operation-Bodies enthalten KEINE Typsyntax und sind sowohl als JS als
 * auch als TS gültig — nur die Präambel unterscheidet sich je nach Zielsprache.
 */

import { getOperation } from '../operations/index.js';

/** Zielsprache des generierten Skripts. */
export type ScriptLanguage = 'js' | 'ts';

/** Eine zu generierende Operation: Typ + bereits geparste Parameter. */
export interface ScriptOperation {
  type: string;
  params: Record<string, unknown>;
}

export interface GenerateScriptResult {
  /** Der vollständige Quelltext (.mjs oder .ts). */
  code: string;
  /** Operation-Typen ohne `generateScript` (im Skript als TODO markiert). */
  unsupported: string[];
}

const HEADER = (lang: ScriptLanguage): string =>
  [
    `// Generated by \`gitbulk init\`. Standalone code-change script (${lang === 'ts' ? 'TypeScript' : 'JavaScript'}) — edit freely.`,
    '//',
    '// GitBulk runs this with the repository as the working directory and sets',
    '// GITBULK_RU / GITBULK_TICKET / GITBULK_BRANCH / GITBULK_SOURCE_BRANCH.',
    '// Only modify files here — GitBulk performs git add / commit / push itself.',
    '// Exit non-zero to signal a failed code change.',
  ].join('\n');

const IMPORTS =
  "import { existsSync, readFileSync, writeFileSync, mkdirSync, rmSync, statSync } from 'node:fs';\n" +
  "import { join, dirname } from 'node:path';";

/** Sprach-spezifische Präambel (Shebang/Imports/Helfer). */
function preamble(lang: ScriptLanguage): string {
  if (lang === 'ts') {
    // Kein Shebang: eine .ts-Datei wird über tsx bzw. Nodes Type-Stripping
    // gestartet, nicht direkt via `node`.
    return [
      HEADER('ts'),
      IMPORTS,
      '',
      'const repoDir: string = process.cwd();',
      "const log = (msg: string): void => console.log('[gitbulk] ' + msg);",
    ].join('\n');
  }
  return [
    '#!/usr/bin/env node',
    HEADER('js'),
    IMPORTS,
    '',
    'const repoDir = process.cwd();',
    "const log = (msg) => console.log('[gitbulk] ' + msg);",
  ].join('\n');
}

/** Rückt jede Zeile um zwei Leerzeichen ein. */
function indent(code: string): string {
  return code
    .split('\n')
    .map((line) => (line.length > 0 ? `  ${line}` : line))
    .join('\n');
}

/**
 * Baut den Quelltext für die gegebene Operationskette in der Zielsprache.
 */
export function generateScript(
  operations: ReadonlyArray<ScriptOperation>,
  language: ScriptLanguage = 'js',
): GenerateScriptResult {
  const unsupported: string[] = [];
  const blocks: string[] = [];

  operations.forEach((op, idx) => {
    const registered = getOperation(op.type);
    const num = idx + 1;

    if (!registered || typeof registered.generateScript !== 'function') {
      unsupported.push(op.type);
      blocks.push(
        `// --- operation #${num}: ${op.type} ---\n` +
          `// NOTE: this operation has no script generator — implement it manually.`,
      );
      return;
    }

    const body = registered.generateScript(op.params as never);
    blocks.push(`// --- operation #${num}: ${op.type} ---\n{\n${indent(body)}\n}`);
  });

  const code = `${[preamble(language), '', ...blocks].join('\n')}\n`;
  return { code, unsupported };
}
