// Generated by `gitbulk init`. Standalone code-change script (TypeScript) — edit freely.
//
// GitBulk runs this with the repository as the working directory and sets
// GITBULK_RU / GITBULK_TICKET / GITBULK_BRANCH / GITBULK_SOURCE_BRANCH.
// Only modify files here — GitBulk performs git add / commit / push itself.
// Exit non-zero to signal a failed code change.
import { existsSync, readFileSync, writeFileSync, mkdirSync, rmSync, statSync } from 'node:fs';
import { join, dirname } from 'node:path';

const repoDir: string = process.cwd();
const log = (msg: string): void => console.log('[gitbulk] ' + msg);

// --- operation #1: delete-file ---
{
  const target = join(repoDir, "README.md");
  if (!existsSync(target)) log("README.md" + ' not present — nothing to delete');
  else if (statSync(target).isDirectory()) log("README.md" + ' is a directory — skipped');
  else { rmSync(target); log('deleted ' + "README.md"); }
}
